os: MinGW
clone_depth: 200

environment:
  global:
    QTDIR: C:\Qt\5.3\mingw482_32
    NSIS_ROOT: C:\nsis
    MINGW: C:\Qt\Tools\mingw482_32

install:
  - appveyor DownloadFile "http://sunet.dl.sourceforge.net/project/nsis/NSIS 2/2.46/nsis-2.46-setup.exe" -FileName nsissetup.exe
  - nsissetup /S /D=%NSIS_ROOT%
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin
  - set TILED_BUILD_DIR=%APPVEYOR_BUILD_FOLDER%
  - set ARCH=32

# Deployment for releases
-
  on:
      appveyor_repo_tag: true
  build_script:
    - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
    - set VERSION=%APPVEYOR_REPO_TAG:~1%
    - echo Building Tiled daily %VERSION%... (from %COMMITNOW%)
    - qmake tiled.pro "CONFIG+=release"
    - mingw32-make
  deploy:
    provider: GitHub
    auth_token:
      secure: 57ahePdHlJPeOX8/MqsIg5ho4x512wvAbwRA7TkXAOav/JTHvkTG5gf8k37/883r
    artifact: /dist\\win\\tiled-.*\.exe/
    draft: true

# Fall back for daily build
-
  build_script:
    - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
    - set VERSION=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
    - echo Building Tiled daily %VERSION%... (from %COMMITNOW%)
    - qmake tiled.pro "CONFIG+=release" "QMAKE_CXXFLAGS+=-DBUILD_INFO_VERSION=%COMMITNOW%"
    - mingw32-make

after_build:
  - pushd %APPVEYOR_BUILD_FOLDER%\dist\win
  - '%NSIS_ROOT%\makensis tiled.nsi'

artifacts:
  - name: Installer
    path: 'dist\win\tiled-*.exe'
